title: Introduction to ATOs

theme: uswds-jekyll

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
