name: Introduction to ATOs
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor/

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: OpenControl
  url: https://open-control.org

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: https://github.com/opencontrol.png
logoalt: OpenControl logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Overview
  url: ''
  internal: true
- text: Lifecycle of a Launch
  url: ato/
  internal: true
  children:
  - text: System Security Plan
    url: ssp/
    internal: true
  - text: Impact Levels
    url: levels/
    internal: true
  - text: Background
    url: background/
    internal: true
  - text: Tips
    url: tips/
    internal: true
- text: Laws
  url: laws/
  internal: true

repos:
- name: Introduction to ATOs
  url: https://github.com/opencontrol/atos

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
