title: OpenControl's Introduction to ATOs

theme: uswds-jekyll

styles:
  - assets/css/custom.css

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: _pages
    values:
      layout: page

github:
  organization: opencontrol
  repository: atos
  default_branch: master
